import asyncio
import logging
import os
from dotenv import load_dotenv

from system.agent.service import Agent
from system.browser.session import BrowserSession
from system.browser.profile import BrowserProfile
from system.llm import ChatGoogle

load_dotenv()
logging.basicConfig(level=logging.INFO)

async def main():
    api_key = os.getenv("GOOGLE_API_KEY")

    # Point to the permanent, dedicated folder inside your MIRA codebase
    dedicated_profile_path = os.path.join(os.getcwd(), "mira_dedicated_profile")
    
    if not os.path.exists(dedicated_profile_path):
        print(f"ERROR: Dedicated profile folder not found at {dedicated_profile_path}")
        print("Please run `python mira_profile_setup.py` first to log in and create the profile!")
        return

    print("=========================================================")
    print("           MIRA: Autonomous Agent Execution              ")
    print("=========================================================")
    print(f"Loading MIRA's dedicated profile from: {dedicated_profile_path}")

    # 🔥 DANGER ZONE: Disable MIRA's disposable /tmp/ safety clone!
    # Because we WANT all history and cookies generated by the agent to permanently save to this dedicated folder.
    BrowserProfile._copy_profile = lambda self: None

    profile = BrowserProfile(
        headless=False,
        user_data_dir=dedicated_profile_path
    )
    
    session = BrowserSession(browser_profile=profile)
    llm = ChatGoogle(model="gemini-2.5-flash", api_key=api_key)

    task_instruction = (
        "Go to gmail.com. You should automatically be signed in. "
        "Find the first/top email in the inbox, click it, and read its contents out loud/summarize it."
    )

    agent = Agent(
        task=task_instruction,
        llm=llm,
        browser_session=session
    )

    try:
        print("\nStarting the autonomous agent connected to your Live Permanent Profile...")
        await session.start()
        
        result = await agent.run()
        print("\n=== Agent Run Completed ===")
        if result.is_successful():
            print("Final Result:", result.final_result())
        else:
            print("Agent did not complete the task successfully.")

        print("\n🟢 Agent finished! Leaving the browser open so you can review...")
        print("Press Ctrl+C in this terminal when you are ready to shut down.")
        
        while True:
            await asyncio.sleep(1)

    except KeyboardInterrupt:
        print("\nExiting gracefully as requested...")
        
    finally:
        print("Cleaning up browser session...")
        await session.stop()

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
